FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

# Install corporate certificates
COPY certificado-corp.crt /usr/local/share/ca-certificates/certificado-corp.crt
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && update-ca-certificates

# Copy everything
COPY . .

# Restore dependencies
RUN dotnet restore

# Command to run tests
ENTRYPOINT ["dotnet", "test", "Sso.IntegrationTests/Sso.IntegrationTests.csproj", "--logger:console;verbosity=detailed"]
